### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by shan1190** [forrestbao/pyeeg#18]
Hi, i`m using python 3.5 and there is error when installing under home directory. Using GIT Bash and python 3.5. Thanks

**Comment by forrestbao** [comment]
@shan1190 , please elaborate what error you got. You may copy from your Terminal and paste to there.

**Comment by Dhananjay09** [comment]
running test
running egg_info
writing pyeeg.egg-info/PKG-INFO
writing dependency_links to pyeeg.egg-info/dependency_links.txt
writing requirements to pyeeg.egg-info/requires.txt
writing top-level names to pyeeg.egg-info/top_level.txt
reading manifest file 'pyeeg.egg-info/SOURCES.txt'
writing manifest file 'pyeeg.egg-info/SOURCES.txt'
running build_ext
test_largest_lyauponov_exponent (tests.test_largest_lyauponov_exponent.LLETests) ... ERROR
test_permutation_entropy (tests.test_permutation_entropy.PermutationEntropyTests) ... ok
test_embedded_sequence_1_4 (tests.test_embedded_sequence.EmbeddedSequenceTests) ... ok
test_embedded_sequence_2_3 (tests.test_embedded_sequence.EmbeddedSequenceTests) ... ok
test_embedded_sequence_4_1 (tests.test_embedded_sequence.EmbeddedSequenceTests) ... ok
test_information_based_similarity (tests.test_information_based_similarity.InformationBasedSimilarityTests) ... ok
test_sampen_against_original_c_test_data (tests.test_sampen.SampEnTests)
Use test data from ... ok
test_sampen_against_predictable_sequence (tests.test_sampen.SampEnTests) ... ok

======================================================================
ERROR: test_largest_lyauponov_exponent (tests.test_largest_lyauponov_exponent.LLETests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhananjay/Desktop/pyeeg-master/tests/test_largest_lyauponov_exponent.py", line 12, in test_largest_lyauponov_exponent
    LLE(data, 2, 4, 1, 1),
  File "/home/dhananjay/Desktop/pyeeg-master/pyeeg/largest_lyauponov_exponent.py", line 75, in LLE
    from embedded_sequence import embed_seq
ModuleNotFoundError: No module named 'embedded_sequence'

----------------------------------------------------------------------
Ran 8 tests in 2.092s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>

**Comment by rosskempner** [comment]
Hi @Dhananjay09 , I also received this error. Were you able to find a solution?

**Comment by Anushka7138** [comment]
Hi @rosskempner & @Dhananjay09 
I'm facing the same issue. Were you able to find a solution? It would be great if you can help me out.

**Comment by chersiakingdom** [comment]
Hi.. @forrestbao @Dhananjay09 @rosskempner 
 @Anushka7138 
I'm also having the same installation error, has anyone solved it?

**Comment by Zq5437** [comment]
Hello ,@Dhananjay09 @rosskempner @Anushka7138 @chersiakingdom 
#38 
I would appreciate it if you can spare some time to see the way I address these problems
Any question is expected^_^
