### ISSUE TITLE
testing not working when installing

### ISSUE THREAD

**Issue by rosskempner** [forrestbao/pyeeg#32]
Hi, I received the following error when testing after installation:

$python setup.py test

running test
running egg_info
writing pyeeg.egg-info/PKG-INFO
writing dependency_links to pyeeg.egg-info/dependency_links.txt
writing requirements to pyeeg.egg-info/requires.txt
writing top-level names to pyeeg.egg-info/top_level.txt
reading manifest file 'pyeeg.egg-info/SOURCES.txt'
writing manifest file 'pyeeg.egg-info/SOURCES.txt'
running build_ext
test_embedded_sequence_1_4 (tests.test_embedded_sequence.EmbeddedSequenceTests) ... ok
test_embedded_sequence_2_3 (tests.test_embedded_sequence.EmbeddedSequenceTests) ... ok
test_embedded_sequence_4_1 (tests.test_embedded_sequence.EmbeddedSequenceTests) ... ok
test_information_based_similarity (tests.test_information_based_similarity.InformationBasedSimilarityTests) ... ok
test_largest_lyauponov_exponent (tests.test_largest_lyauponov_exponent.LLETests) ... ERROR
test_permutation_entropy (tests.test_permutation_entropy.PermutationEntropyTests) ... ok
test_sampen_against_original_c_test_data (tests.test_sampen.SampEnTests)
Use test data from ... ok
test_sampen_against_predictable_sequence (tests.test_sampen.SampEnTests) ... ok

======================================================================
ERROR: test_largest_lyauponov_exponent (tests.test_largest_lyauponov_exponent.LLETests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ross/Desktop/Documents/Research/contrasting_6_meditation_practices_EEG/pyeeg/tests/test_largest_lyauponov_exponent.py", line 12, in test_largest_lyauponov_exponent
    LLE(data, 2, 4, 1, 1),
  File "/Users/ross/Desktop/Documents/Research/contrasting_6_meditation_practices_EEG/pyeeg/pyeeg/largest_lyauponov_exponent.py", line 75, in LLE
    from embedded_sequence import embed_seq
ModuleNotFoundError: No module named 'embedded_sequence'

----------------------------------------------------------------------
Ran 8 tests in 3.996s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>

**Comment by esskay0000** [comment]
Same problem. Did you get any solution? @rosskempner

**Comment by rosskempner** [comment]
No, I did not. I had to use different packages.

**Comment by rockandrolla13** [comment]
same problem as well. precisely same error
======================================================================
ERROR: test_largest_lyauponov_exponent (tests.test_largest_lyauponov_exponent.LLETests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ak/GitRepos/pyeeg/tests/test_largest_lyauponov_exponent.py", line 12, in test_largest_lyauponov_exponent
    LLE(data, 2, 4, 1, 1),
  File "/home/ak/GitRepos/pyeeg/pyeeg/largest_lyauponov_exponent.py", line 75, in LLE
    from embedded_sequence import embed_seq
ModuleNotFoundError: No module named 'embedded_sequence'

**Comment by Zq5437** [comment]
@rosskempner @andreas-koukorinis 
#38 
May be this is too late for you to be informed , but I just want to show you the way I address these problems . 
Any question is expected .
